Coalesce boolean arguments to actual Boolean type instead of string
infinitered/gluegun pull request #763
Opened 2022-08-25 18:01 UTC by joshuayoes

2022-08-25 18:07 UTC, joshuayoes commented
I've added failing tests to demonstrate desired behavior

2022-08-25 18:21 UTC, joshuayoes commented
It also may be better to take a [PR like this](https://github.com/infinitered/gluegun/pull/464), where we could provide the `yargs-parser` object optionally, and then allow for opting into coalescing options

2022-08-25 18:33 UTC, joshuayoes commented
Got some input from Jamon. Gluegun already doesn't have great type-safety guarantees on command parsing, so this quality of life improvement would be worth a potentially breaking change

2022-08-25 23:44 UTC, joshuayoes commented
![Screen Shot 2022-08-25 at 4 43 04 PM](https://user-images.githubusercontent.com/37849890/186787672-838f89b6-dd24-4350-9165-2e911fdc5f5f.png)
https://dev.azure.com/infinitered/gluegun/_build?view=runs

I think something changed about ts-node or typescript dependency between now and May. 

I don't think these changes are causing this issue, but I will investigate more before merging

2022-08-26 04:19 UTC, jamonholmgren requested changes
Good to go (after CI fixed)

I'll merge & release once CI is fixed and you slim down that helper function.

2022-08-26 04:19 UTC, jamonholmgren commented on src/toolbox/parameter-tools.ts
> +import type yargsParser from 'yargs-parser'
Smart to use an `import type` here.

2022-08-26 04:19 UTC, jamonholmgren commented on src/toolbox/parameter-tools.ts
> +    }),
I'd use the simplified version here that I mentioned in the related Ignite PR.

2023-09-28 17:52 UTC, jamonholmgren commented
Merged into #783 since this will be a breaking change too.

2023-09-28 17:53 UTC, closed without merging